Lecture 3 pdp add to cart
ponchik18/phoneshop-servlet-api pull request #3
Opened 2023-05-13 05:08 UTC by ponchik18

2023-05-15 21:01 UTC, marharyta-aheyanka requested changes

2023-05-15 21:01 UTC, marharyta-aheyanka commented on src/main/java/com/es/phoneshop/model/cart/DefaultCartService.java
> +    private static DefaultCartService instance;
The same issue i mentioned prev time regarding singleton implementation

2023-05-15 21:01 UTC, marharyta-aheyanka commented on src/main/java/com/es/phoneshop/model/cart/DefaultCartService.java
> +        CartItem foundedCartItem = cart.getItems().stream()
founded?

2023-05-15 21:01 UTC, marharyta-aheyanka commented on src/main/java/com/es/phoneshop/model/cart/DefaultCartService.java
> +        CartItem foundedCartItem = cart.getItems().stream()
better use Optional<CartItem> and then check if it's present

2023-05-15 21:01 UTC, marharyta-aheyanka commented on src/main/java/com/es/phoneshop/web/ProductDetailsPageServlet.java
> +            request.setAttribute("error", "Invalid quantity "+exception.getQuantity()+". Available only "+exception.getAvailableStock());
please follow the formatting rules

2023-05-15 21:01 UTC, marharyta-aheyanka commented on src/main/java/com/es/phoneshop/model/cart/DefaultCartService.java
> +    public synchronized Cart getCart(HttpServletRequest request) {
Is it the best option of the synchronization?

2023-05-15 21:01 UTC, marharyta-aheyanka commented on src/main/java/com/es/phoneshop/model/cart/DefaultCartService.java
> +        CartItem foundedCartItem = cart.getItems().stream().filter(cartItem -> cartItem.getProduct().getId().equals(productId)).filter(cartItem -> cartItem.getProduct().getStock() > 0).findAny().orEl
What is the purpose of the change?

2023-05-15 21:01 UTC, marharyta-aheyanka commented on src/main/java/com/es/phoneshop/web/ProductDetailsPageServlet.java
> +        } catch (ParseException exception) {
i recommend to move the validation logic into separate method

2023-05-15 21:01 UTC, marharyta-aheyanka commented on src/main/java/com/es/phoneshop/web/ProductListPageServlet.java
> +        request.setAttribute("products", productDao.findProducts(search, Optional.ofNullable(sortField).map(SortField::valueOf).orElse(null), Optional.ofNullable(sortOrder).map(SortOrder::valueOf).or
What is the purpose of the change?

2023-05-15 21:01 UTC, marharyta-aheyanka commented on src/main/java/com/es/phoneshop/model/history/ProductsTrackingHistory.java
> +public class ProductsTrackingHistory {
Why doesn't this class implement any interface?

2023-05-17 06:52 UTC, alexeyburak commented on src/test/java/com/es/phoneshop/model/history/DefaultProductsTrackingHistoryServiceTest.java
> +        for(int i=testProducts.size()-MAX_SIZE_HISTORY_LIST; i<testProducts.size();i++) {
formatting!

2023-05-17 06:52 UTC, alexeyburak commented on src/test/java/com/es/phoneshop/model/cart/DefaultCartServiceTest.java
> +        cartService.add(cart, productId, quantity,"");
StringUtils.EMPTY

2023-05-17 21:51 UTC, marharyta-aheyanka requested changes

2023-05-17 21:51 UTC, marharyta-aheyanka commented on src/main/java/com/es/phoneshop/model/history/ProductHistoryList.java
>  public class ProductHistoryList {
Change the name to smth that doesn't end with List otherwise it seems to be List implementation

2023-05-17 21:51 UTC, marharyta-aheyanka commented on src/main/java/com/es/phoneshop/web/ProductDetailsPageServlet.java
> +            setErrorAndRedirect(request, response, "Invalid quantity " +
"forward" is more appropriate then "redirect"

2023-05-17 21:51 UTC, marharyta-aheyanka commented on src/main/java/com/es/phoneshop/service/iml/DefaultProductsTrackingHistoryService.java
> +        synchronized (sessionId.intern()) {
there is no need to synchronize by session, you can synchronize by productHistoryList

2023-05-17 21:51 UTC, marharyta-aheyanka commented on src/main/java/com/es/phoneshop/service/iml/DefaultCartService.java
> +    public void add(Cart cart, Long productId, int quantity, String sessionId) throws OutOfStockException {
there is no need to synchronize by session, you can synchronize by cart

2023-05-18 16:04 UTC, merged